#!/bin/bash

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║       🚀  BLUE-GREEN DEPLOYMENT - DEMO LISTA PARA EXPONER     ║"
echo "║                                                                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📊 ESTADO ACTUAL:"
echo "  ✅ BLUE en puerto 8080 → ACTIVA (recibiendo tráfico)"
echo "  ✅ Nginx en puerto 80  → Proxy reverso funcionando"
echo "  ✅ GREEN en puerto 8081 → LISTO PARA DESPLEGAR"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📋 FLUJO DE EXPOSICIÓN (Ejecutar en orden):"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "🔵 PASO 1: Verificar que BLUE está activa"
echo "   $ curl http://127.0.0.1/api/instance"
echo "   Resultado esperado: BLUE"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "💚 PASO 2: Health check de BLUE"
echo "   $ curl http://127.0.0.1/actuator/health"
echo "   Resultado: status UP"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "🟢 PASO 3: DESPLEGAR GREEN en puerto 8081"
echo "   $ src/scripts/deploy.sh"
echo "   Resultado:"
echo "     - Inicia GREEN en 8081"
echo "     - Valida health check (espera ~30 segundos)"
echo "     - Cambia tráfico de Nginx a GREEN"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "✅ PASO 4: Verificar que GREEN está activa"
echo "   $ curl http://127.0.0.1/api/instance"
echo "   Resultado esperado: GREEN (a través de Nginx)"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "🧪 PASO 5: Ejecutar E2E Test"
echo "   $ EXPECTED_INSTANCE=GREEN src/scripts/e2e-test.sh"
echo "   Resultado: E2E OK: GREEN respondió detrás de Nginx"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "📜 PASO 6: Ver logs de GREEN (Mientras se ejecuta)"
echo "   $ tail -f app-8081.log"
echo "   Presionar Ctrl+C para salir"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "↩️  PASO 7 (OPCIONAL): Hacer rollback a BLUE"
echo "   $ src/scripts/rollback.sh"
echo "   Resultado: Tráfico vuelve a BLUE:8080"
echo "   (GREEN sigue corriendo para investigar logs)"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📍 UBICACIÓN DEL PROYECTO:"
echo "   /mnt/c/Users/Camilo Sarmiento/Music/DIPLO PROYECTO/Proyecto final 4/proyecto-final"
echo ""
echo "🎯 OBJETIVO DE LA DEMO:"
echo "   Mostrar cómo Blue-Green permite desplegar nuevas versiones"
echo "   sin downtime, con validación automática y rollback instantáneo."
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✨ ¡TODO LISTO PARA EXPONER!"
echo ""
