#!/bin/bash

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                                                            ║"
echo "║    ✅ BLUE-GREEN DEPLOYMENT - COMPLETAMENTE LISTO         ║"
echo "║                                                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 VERIFICACIÓN FINAL:"
echo ""
echo "1. BLUE respondiendo en :8080"
curl -s http://127.0.0.1:8080/api/instance
echo ""
echo "2. Nginx proxy en :80"
curl -s http://127.0.0.1/api/instance
echo ""
echo "3. Health check"
curl -s http://127.0.0.1/actuator/health | head -c 60
echo "..."
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📁 Archivos Creados:"
echo ""
echo "  📄 PRESENTACION.md / Blue-Green-Deployment.pptx"
echo "     → Slides con conceptos y arquitectura"
echo ""
echo "  📄 DEMO_FLUJO.md / DEMO_Flujo_Completo.pptx"
echo "     → Diapositivas paso a paso de la demo"
echo ""
echo "  📄 GUIA_RAPIDA_EXPOSICION.md ⭐"
echo "     → GUÍA DE REFERENCIA RÁPIDA (LEER ESTO)"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "🎯 FLUJO PARA EXPONER EN VIVO:"
echo ""
echo "PASO 1️⃣  (30s) - Ver BLUE activa"
echo "   $ curl http://127.0.0.1/api/instance"
echo "   → BLUE"
echo ""
echo "PASO 2️⃣  (45s) - Desplegar GREEN"
echo "   $ src/scripts/deploy.sh"
echo "   → Inicia GREEN, valida, cambia Nginx"
echo ""
echo "PASO 3️⃣  (15s) - Verificar GREEN activa"
echo "   $ curl http://127.0.0.1/api/instance"
echo "   → GREEN"
echo ""
echo "PASO 4️⃣  (10s) - E2E Test"
echo "   $ EXPECTED_INSTANCE=GREEN src/scripts/e2e-test.sh"
echo "   → E2E OK"
echo ""
echo "PASO 5️⃣  (15s) - Ver logs"
echo "   $ tail -f app-8081.log"
echo "   → Ctrl+C para salir"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "⏱️  TIEMPO TOTAL: 25 minutos"
echo "   • Explicación: 2 min"
echo "   • Demo: 15-20 min"  
echo "   • Preguntas: 5 min"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "✨ ¡LISTO PARA EXPONER!"
echo ""
